Update nunjucks.md
yeoman/generator-webapp pull request #753
Opened 2019-03-01 09:03 UTC by jaysunwalter123

This could do with improvement I'm sure but it's working for me thus far. I'm not at all a js pro, I slowly worked through it, converting from the old recipe as well as I could. Because I don't fully understand what every little bit does my commenting is a little incomplete. Hopefully this will help anyone else that relies on this setup that I personally have used for years.

2019-03-04 13:26 UTC, silvenon requested changes
Thanks Jason! This is looking pretty good, some more updates are necessary, though 😃

2019-03-04 13:26 UTC, silvenon commented on docs/recipes/nunjucks.md
> ++ watch('app/**/*.{html,njk}', views);
You probably meant to call `viewsreload` here, but instead I suggest removing `viewsreload` function entirely and simply calling `server.reload` directly:

```js
watch('app/**/*.{html,njk}', server.reload);
```

2019-03-04 13:26 UTC, silvenon commented on docs/recipes/nunjucks.md
> +Edit your `serve` task so that editing `.html` and `.njk` files triggers the `viewsreload` function:
This description needs to be updated to something more accurate:

> Compile `.njk` files before running the server

But instead I suggest deleting this section and moving the code below to step 6, which contains old `gulpfile.js` code and needs to be updated anyway. You can update its title so the whole 6th step section goes something like this:

> ### 6. Add `views` as a dependency of both `serve` and `build`
>
> ```diff
>  if (isDev) {
> -  serve = series(clean, parallel(styles, scripts, fonts), startAppServer);
> +  serve = series(clean, parallel(views, styles, scripts, fonts), startAppServer);
>  } ...
> ```
>
> ```diff
>  const build = series(
>    parallel(
>     lint,
> -   series(parallel(styles, scripts), html),
> +   series(parallel(views, styles, scripts), html),
>     images,
>     fonts,
>     extras
>    ),
>    measureSize
>  );
> ```

2019-03-04 13:26 UTC, silvenon commented on docs/recipes/nunjucks.md
> +}
Best remove this extra `}` to avoid confusion.

2019-10-28 19:10 UTC, UlisesGascon commented
Maybe this PR was the same as #766. Should we remix and merge them in a separate branch, @silvenon ? I can handle that if you agree 👍

2019-11-16 17:38 UTC, silvenon commented
Since we merged another PR that updated the Nunjucks recipe, I'll close this, but congratulations for the contribution @jaysunwalter123!

2019-11-16 17:38 UTC, closed without merging